name: Flutter Setup

on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: '3.24.4'
    outputs:
      result:
        description: "The result of the Flutter setup"
        value: ${{ jobs.setup.outputs.result }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.flutter-setup.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Flutter
        id: flutter-setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get